### PR TITLE
issue: register_check_parameters() got an unexpected keyword argument 'match_type'

### PR DESCRIPTION
**Pull request by schoekek**
This is running under 1.2.6p14

### CODE REVIEW

**Comment by seppovic** [comment]
seems that match_type was introduced in 1.2.7 branch and is not available in 1.2.6
I am going to check if your patches work in 1.2.7 too and merge your commits if that's the case.

**Comment by seppovic** [comment]
I wonder why the vendor is using named parameters here?! I will merge this and update all the pakets asap.
